### ISSUE TITLE
Evaluate how hard it would be to port to linux.

### ISSUE THREAD

**Issue by Angelo1211** [Angelo1211/HybridRenderingEngine#27]
Given that I have been using CMAke for building, SDL2 for the hardware abstraction layer and OpenGL it might not be too awful to port the project to linux. This is not super high priority however.

**Comment by jpbruyere** [comment]
[My fork](https://github.com/jpbruyere/HybridRenderingEngine/tree/linux_compiled) (linux_compiled branch) compiled and run on Debian 10. See the diff for details.

**Comment by Angelo1211** [comment]
@jpbruyere Thanks! Unfortunaly I'm closing this project now since it is not actively maintained anymore.
