### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by zinwalin** [Angelo1211/HybridRenderingEngine#31]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ASSIMP_LIBRARY_DEBUG
    linked by target "hybridRenderer" in directory C:/src/HybridRenderingEngine
ASSIMP_LIBRARY_RELEASE
    linked by target "hybridRenderer" in directory C:/src/HybridRenderingEngine

![image](https://user-images.githubusercontent.com/5416196/69405276-1f39e500-0d64-11ea-8508-1923c39fbf90.png)

**Comment by VectorL1990** [comment]
I have the same problem, have you solved it yet?
